[project]
name = "dojo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mongoengine>=0.29.1",
    "polars>=1.31.0",
    "pydantic>=2.11.7",
]
